development: true
#Configuration section for result image
#supported values are replicas
worker:
  replicas: 1

#Configuration section for db(postgres) image
#supported values are replicas,serviceType,nodePort,containerPort,mountName
db:
  replicas: 1

#Configuration section for redis image
#supported values are replicas,serviceType,nodePort,containerPort,mountName
redis:
  replicas: 1

#Configuration section for result image
#supported values are replicas,hostPort,nodePort,containerPort
result:


#Configuration section for vote image
#supported values are replicas,hostPort,nodePort,containerPort
vote:

elasticsearch:
  antiAffinity: "soft"
  replicas: 1
  minimumMasterNodes: 1

  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "standard"
    resources:
      requests:
        storage: 20Gi

  readinessProbe:
    initialDelaySeconds: 240
    periodSeconds: 200

filebeat:
  extraInitContainers: |
    - name: waitforelasticsearch
      image: busybox:1.31.1
      command: ['sh', '-c', 'sleep 360']
  readinessProbe:
    initialDelaySeconds: 360
    periodSeconds: 120

metricbeat: 
  extraInitContainers: |
    - name: waitforelasticsearch
      image: busybox:1.31.1
      command: ['sh', '-c', 'sleep 360']
  readinessProbe:
    initialDelaySeconds: 360
    periodSeconds: 120