apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  type: {{ if .Values.db -}} {{- default "ClusterIP" .Values.db.serviceType -}}{{- else -}}"ClusterIP"{{- end }}
  ports:
  - name: "db-service"
    port: {{ if .Values.db -}} {{- default 5432 .Values.db.containerPort}} {{- else -}}5432{{- end }}
    targetPort: {{ if .Values.db -}} {{- default 5432 .Values.db.containerPort}} {{- else -}}5432{{- end }}
    {{ if and .Values.db (eq .Values.db.serviceType "Nodeport") -}}
    nodePort: {{ if .Values.db -}} {{- default 31004 .Values.db.nodePort -}}{{- else -}}31004{{- end -}}
    {{- end }}
  selector:
    app: db
  