apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  #namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: dockersamples/examplevotingapp_worker
        name: worker
        # env:
        # - name: DB_CONNECTION_STRING
        #   value: Server=db;Database=postgres;Username=postgres;Password=postgres;Database=postgres; 
